### ISSUE TITLE
[EPIC] Quest Category 2: Implement existing ICS specs into Solidity implementation

### ISSUE THREAD

**Issue by tmsdkeys** [test-pit/game-of-rollups#5]
In the second category for Game of Rollups quests, you'll take an existing application protocol fro the [Interchain Standards (ICS) repo](https://github.com/cosmos/ibc) and implement an implementation in Solidity.

- [ ] ICS 20: Fungible Token Transfer
- [ ] ICS 27: Interchain Accounts
- [ ] ICS 31: Cross-chain Queries
- [ ] ICS 32: Interchain Queries
- [ ] ICS 721: Non-Fungible Token Transfer
